#!/bin/sh

PYRUN=.venv/bin/python3

rm handbook/migrations/0001_initial.py

eval "$PYRUN manage.py migrate --fake" 2>/dev/null
eval "$PYRUN manage.py makemigrations"
eval "$PYRUN manage.py migrate"

eval "$PYRUN manage.py runserver 127.0.0.1:7289 --insecure"

