#!/bin/sh

PYRUN=.venv/bin/python3

rm handbook/migrations/0001_initial.py > /dev/null

eval "$PYRUN manage.py migrate --fake" > /dev/null
eval "$PYRUN manage.py makemigrations"
eval "$PYRUN manage.py migrate"

eval "$PYRUN manage.py runserver 127.0.0.1:7289"

