# Generated by Django 4.1.12 on 2023-10-27 21:09

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRace',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name_rus', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.CharField(max_length=255)),
                ('countries', djongo.models.fields.JSONField()),
                ('lands', djongo.models.fields.JSONField()),
                ('langs', djongo.models.fields.JSONField()),
                ('religions', djongo.models.fields.JSONField()),
            ],
        ),
    ]
