# Generated by Django 4.2.6 on 2023-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2047)),
            ],
        ),
    ]
