# Generated by Django 4.1.12 on 2023-10-28 12:29

from django.db import migrations
import djongo.models.fields
import handbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerace',
            name='create',
            field=djongo.models.fields.ArrayField(default=[], model_container=handbook.models.Spec, model_form_class=handbook.models.SpecForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerace',
            name='spec',
            field=djongo.models.fields.ArrayField(default=[], model_container=handbook.models.Spec, model_form_class=handbook.models.SpecForm),
            preserve_default=False,
        ),
    ]
