# Generated by Django 4.1.12 on 2023-10-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerace',
            old_name='id',
            new_name='_id',
        ),
    ]
