# Generated by Django 4.2.6 on 2023-10-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_gamerace_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerace',
            name='img_path',
        ),
    ]
