# Generated by Django 3.1.12 on 2023-10-28 12:51

from django.db import migrations
import djongo.models.fields
import handbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_gamerace_create_gamerace_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerace',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='gamerace',
            name='lands',
        ),
        migrations.RemoveField(
            model_name='gamerace',
            name='langs',
        ),
        migrations.RemoveField(
            model_name='gamerace',
            name='religions',
        ),
        migrations.AddField(
            model_name='gamerace',
            name='info',
            field=djongo.models.fields.ArrayField(default=[], model_container=handbook.models.Spec, model_form_class=handbook.models.SpecForm),
            preserve_default=False,
        ),
    ]
