# Generated by Django 3.1.12 on 2023-10-29 11:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_auto_20231028_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hits', models.IntegerField()),
                ('max_hits', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('max_energy', models.IntegerField()),
            ],
        ),
    ]
