# Generated by Django 4.2.6 on 2023-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_remove_gamerace_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerace',
            name='img_path',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
